/** DualisCapax payment rails. Payments CLOSED (freeze). Stripe retired. No public pay-to or wallet address. Do not re-add addresses or links here without an owner vote. */
window.DC_PAYMENTS = {
  interac_enabled: false,
  eft_enabled: false,
  sri_enabled: false,
  fuel_enabled: false,
  onboard_enabled: false,
  stripe_enabled: false,
  stripe_retired: true,
  checkout_open: false,
  research: "",
  cost_reduction: "",
  capacity: "",
  fuel: "",
  ubi: "",
  crypto_enabled: false,
  fulfill_worker: "",
  thanks: "/pay/thanks.html",
  ai_doge: "",
  research_xrp: "",
  research_zec: "",
  research_sol: "",
  research_eth: "",
  research_pol: "",
  research_link: "",
  research_bsc: "",
  research_dot: "",
  research_dgb: "",
  research_bch: ""
};
