name = "dualiscapax-stripe-fulfill"
main = "index.js"
compatibility_date = "2026-08-30"

[[d1_databases]]
binding = "DB"
database_name = "dualiscapax-fulfillments"
database_id = "d1-dualiscapax-fulfillments-id"
