from __future__ import annotations
from enum import Enum

class EpistemicState(str, Enum):
    CLAIMED = "CLAIMED"
    OBSERVED = "OBSERVED"
    MEASURED = "MEASURED"
    REPRODUCED = "REPRODUCED"
    INDEPENDENTLY_VERIFIED = "INDEPENDENTLY_VERIFIED"
    ADVERSARIALLY_SURVIVED = "ADVERSARIALLY_SURVIVED"
    PROVENANCE_COMPLETE = "PROVENANCE_COMPLETE"
    AUTHORIZED = "AUTHORIZED"
    PROMOTABLE = "PROMOTABLE"
    UNRESOLVED = "UNRESOLVED"
    QUARANTINED = "QUARANTINED"
    CONTRADICTED = "CONTRADICTED"
    RETIRED = "RETIRED"
    EXPIRED = "EXPIRED"
    BLOCKED = "BLOCKED"

NEGATIVE_TERMINAL = frozenset({EpistemicState.QUARANTINED, EpistemicState.CONTRADICTED, EpistemicState.RETIRED, EpistemicState.EXPIRED, EpistemicState.BLOCKED})
FORWARD = {
    EpistemicState.CLAIMED: EpistemicState.OBSERVED,
    EpistemicState.OBSERVED: EpistemicState.MEASURED,
    EpistemicState.MEASURED: EpistemicState.REPRODUCED,
    EpistemicState.REPRODUCED: EpistemicState.INDEPENDENTLY_VERIFIED,
    EpistemicState.INDEPENDENTLY_VERIFIED: EpistemicState.ADVERSARIALLY_SURVIVED,
    EpistemicState.ADVERSARIALLY_SURVIVED: EpistemicState.PROVENANCE_COMPLETE,
    EpistemicState.PROVENANCE_COMPLETE: EpistemicState.AUTHORIZED,
    EpistemicState.AUTHORIZED: EpistemicState.PROMOTABLE,
}
LATERAL_NEGATIVE = frozenset({EpistemicState.UNRESOLVED, EpistemicState.QUARANTINED, EpistemicState.CONTRADICTED, EpistemicState.RETIRED, EpistemicState.EXPIRED, EpistemicState.BLOCKED})
EVIDENCE_FORBIDDEN_STATES = frozenset({EpistemicState.PROMOTABLE, EpistemicState.AUTHORIZED, EpistemicState.PROVENANCE_COMPLETE})

class EffectOutcome(str, Enum):
    EXECUTED = "EXECUTED"
    FAILED = "FAILED"
    INDETERMINATE = "INDETERMINATE"

class SurfaceClass(str, Enum):
    AUTHORITATIVE_STATE = "AUTHORITATIVE_STATE"
    PROJECTION = "PROJECTION"
    CACHE = "CACHE"
    DISPLAY = "DISPLAY"
    RECEIPT = "RECEIPT"
    LEDGER = "LEDGER"
    DOCUMENTATION = "DOCUMENTATION"
    UI_STATE = "UI_STATE"
    LOCAL_STORAGE = "LOCAL_STORAGE"
    SESSION_STATE = "SESSION_STATE"
