/** DualisCapax payment rails. Checkout CLOSED. Stripe Payment Links parked (removed from public plate). No public pay-to or wallet address. */
window.DC_PAYMENTS = {
  interac_enabled: false,
  eft_enabled: false,
  sri_enabled: false,
  fuel_enabled: false,
  onboard_enabled: false,
  stripe_enabled: false,
  stripe_retired: true,
  jacket_open: false,
  checkout_open: false,
  research: "",
  cost_reduction: "",
  capacity: "",
  fuel: "",
  fuel_links: {
    fuel_10: null,
    fuel_40: null,
    fuel_120: null,
    fuel_320: null,
    fuel_1000: null
  },
  leaf: "",
  field: "",
  trunk: "",
  branch: null,
  atlas: null,
  edu_leaf: null,
  crypto_enabled: false,
  fulfill_worker: "",
  thanks: "/pay/thanks.html",
  research_btc: "",
  research_eth: "",
  research_sol: ""
};
