var BOARDS=[
  {id:'hpedsb',name:'Hastings and Prince Edward DSB',mail:'@hpedsb.on.ca',site:'https://www.hpeschools.ca'},
  {id:'alcdsb',name:'Algonquin and Lakeshore Catholic DSB',mail:'@alcdsb.on.ca',site:'https://www.alcdsb.on.ca'},
  {id:'limestone',name:'Limestone DSB',mail:'@limestone.on.ca',site:'https://www.limestone.on.ca'}
];
var SCHOOLS={
hpedsb:[
"Athol-South Marysburgh Public School","Bayside Public School","Bayside Secondary School","Bird's Creek Public School","C.M.L. Snider School","Centennial Secondary School","Central Hastings School","Coe Hill School","Deseronto Public School","Easthill Elementary School","Eastside Secondary School","Foxboro Public School","Frankford Public School","Harmony Public School","Harry J. Clarke Public School","Hermon Public School","Kente Public School","Madoc Township Public School","Marmora Public School","Massassaga-Rednersville Public School","Maynooth Public School","North Hastings High School","North Trenton Public School","Park Dale School","Prince Charles Public School (Trenton)","Prince Charles School (Belleville)","Prince Edward Collegiate Institute","Prince of Wales Public School","Sir John A. Macdonald School","Sophiasburgh Central School","Stirling Public School","Susanna Moodie Elementary School","Trent River Public School","Trenton High School","Tweed Elementary School","Tyendinaga Public School","V.P. Carswell Elementary School","York River Public School"
],
alcdsb:[
"Archbishop O'Sullivan Catholic School","École Catholique Cathédrale","Georges Vanier Catholic School","Holy Name Catholic School","Holy Name of Mary Catholic School","Holy Rosary Catholic School","J.J. O'Neill Catholic School","John XXIII Catholic School","Mother Teresa Catholic School","Our Lady of Fatima Catholic School","Our Lady of Lourdes Catholic School","Our Lady of Mercy Catholic School","Our Lady of Mount Carmel Catholic School","Sacred Heart Catholic School","St. Carthagh Catholic School","St. Francis of Assisi Catholic School","St. Genevieve Catholic School","St. Gregory Catholic School","St. Joseph Catholic School","St. Marguerite Bourgeoys Catholic School","St. Martha Catholic School","St. Mary Catholic School","St. Michael Catholic School","St. Patrick Catholic School","St. Paul Catholic School","St. Peter Catholic School","St. Thomas More Catholic School","Holy Cross Catholic Secondary School","Nicholson Catholic College","Regiopolis-Notre Dame Catholic High School","St. Paul Catholic Secondary School","St. Theresa Catholic Secondary School"
],
limestone:[
"Amherst Island Public School","Amherstview Public School","Bath Public School","Bayridge Public School","Bayridge Secondary School","Calvin Park Public School","Cataraqui Woods Elementary School","Centennial Public School","Central Public School","Centreville Public School","Clarendon Central Public School","Collins Bay Public School","Denbigh Public School","École Maple Elementary School","Elginburg & District Public School","Enterprise Public School","Ernestown Intermediate and Secondary School","Fairfield Elementary School","First Avenue Public School","Frontenac Public School","Frontenac Secondary School","Glenburnie Public School","Granite Ridge Education Centre","H H Langford Public School","Harrowsmith Public School","Hinchinbrooke Public School","Holsgrove Public School","James R Henderson Public School","John Graves Simcoe Public School","Joyceville Public School","Kingston Secondary School","La Salle Secondary School","Lancaster Drive Public School","Land O Lakes Public School","Lord Strathcona Public School","Loughborough Public School","Loyalist Collegiate and Vocational Institute","Marysville Public School","Module Vanier Elementary School","Napanee District Secondary School","Newburgh Public School","North Addington Education Centre","Odessa Public School","Perth Road Public School","Polson Park Public School","Prince Charles Public School","R Gordon Sinclair Memorial Public School","Rideau Heights Public School","Rideau Public School","Sandhurst Public School","Selby Public School","Sharbot Lake Intermediate School","Storrington Public School","Sydenham High School","Sydenham Public School","Tamworth Elementary School","The Prince Charles School","Truedell Public School","Welborne Avenue Public School","Winston Churchill Public School","Yarker Public School"
]
};
